# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: pyproject-template # EDIT
site_url: https://WSH032.github.io/pyproject-template/ # EDIT

repo_url: https://github.com/WSH032/pyproject-template/ # EDIT
repo_name: WSH032/pyproject-template # EDIT

edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    logo: octicons/rocket-24 # EDIT: or do nothing
  favicon: images/rocket-24.svg # EDIT: or do nothing
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.tooltips
    - navigation.top
    # - navigation.expand
    # - navigation.tracking
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  # - offline
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # https://mkdocstrings.github.io/python/usage/#import
          import: [] # EDIT
          options:
            docstring_style: google
          paths: [src]
  # Remember: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin#note-when-using-build-environments
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: WSH032/pyproject-template # EDIT
      branch: main

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WSH032/ # EDIT

watch:
  - src/
  - README.md
  - CONTRIBUTING.md
  - CHANGELOG.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Don't change the name "reference/"
# It's used in scripts/gen_ref_pages.py
nav:
  - Home: index.md
  - Usage: [] # EDIT
  - API Reference: reference/
  - CONTRIBUTING:
      - CONTRIBUTING/CONTRIBUTING.md
  - CHANGELOG:
      - CHANGELOG/CHANGELOG.md
