# WARNING: Do not change the name of this file, keep `lint-test.yml`.
# `workflow_call` needs the name of the workflow file to work.

name: Lint check and test

# We only automatically run checks for PRs.
# It is best to avoid direct commits to the main branch, instead make a PR for checks.
# For the pushes to the main branch, the checks is done by `publish.yml` when publish.
on:
  pull_request:
  workflow_dispatch:
  # NOTE: set `secrets: inherit` when call this workflow from other workflow.
  workflow_call:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          # Issue ref: https://github.com/actions/setup-python/issues/436
          cache: "pip"
      # setup and cache envs
      - name: setup and cache envs
        id: setup-envs
        uses: ./.github/actions/setup-envs
        with:
          python-version: ${{ steps.setup-python.outputs.python-version }}
          python-path: ${{ steps.setup-python.outputs.python-path }}
          create-default-env: true
          cache-default-env: true
          create-fmt-env: true
          cache-fmt-env: true

      - name: Lint check and type check
        # keep the hook name consistent with `ci.skip` in `.pre-commit-config.yaml`
        run: |
          pre-commit run fmt-check -a
          pre-commit run type-check -a

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Issue ref: https://github.com/actions/setup-python/issues/436
          cache: "pip"
      # setup and cache envs
      - name: setup and cache envs
        id: setup-envs
        uses: ./.github/actions/setup-envs
        with:
          python-version: ${{ steps.setup-python.outputs.python-version }}
          python-path: ${{ steps.setup-python.outputs.python-path }}
          create-default-env: true
          cache-default-env: true

      - name: Test
        # Prevent unknown errors from causing long-term blockage of ci during testing
        # can be adjusted according to the actual test time
        timeout-minutes: 5
        run: |
          hatch run test
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true

  # https://github.com/marketplace/actions/alls-green#why
  lint-test-all-green: # This job does nothing and is only used for the branch protection
    if: always() # IMPORTANT: mandatory
    needs:
      - lint-check
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
